//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by DEMO.RC
//
#define IDM_BOX                         101
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define IDM_BLOCK                       102
#define _APS_NEXT_RESOURCE_VALUE        102
#define IDM_RETAIN                      103
#define IDM_ABOUT                       104
#define _APS_NEXT_CONTROL_VALUE         1000
