//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by XTENSION.RC
//
#define IDM_STATUSWIN                   10
#define IDM_GETFILESELLFN               15
#define IDM_GETDRIVEINFO                20
#define IDM_GETFOCUS                    25
#define IDM_RELOADEXTENSIONS            30
#define IDM_REFRESHWINDOW               35
#define IDM_REFRESHALLWINDOWS           40
#define IDM_ABOUTEXT                    45
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define _APS_NEXT_RESOURCE_VALUE        102
#define IDD_SELFILECOUNT                201
#define IDD_SELFILESIZE                 202
#define IDD_PATH                        206
#define IDD_VOLUME                      207
#define IDD_SHARE                       208
#define IDD_TOTALSPACE                  209
#define IDD_FREESPACE                   210
#define _APS_NEXT_CONTROL_VALUE         1000
