//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by HELPEX.RC
//
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_CONTROL_VALUE         1000

/* file menu items */

#define     IDM_NEW      100
#define     IDM_OPEN     101
#define     IDM_SAVE     102
#define     IDM_SAVEAS   103
#define     IDM_PRINT    104
#define     IDM_EXIT     105

/* edit menu items */

#define     IDM_UNDO     200
#define     IDM_CUT      201
#define     IDM_COPY     202
#define     IDM_PASTE    203
#define     IDM_CLEAR    204

/* define help items */

#define     IDM_ABOUT          300
#define     IDM_HELP_INDEX     301
#define     IDM_HELP_KEYBOARD  302
#define     IDM_HELP_HELP      303
