//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by DRAGDROP.RC
//
#define STRING_LEN                      10
#define FILE_NAME_LENGTH                45
#define IDM_ABOUT                       100
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define _APS_NEXT_RESOURCE_VALUE        102
#define IDM_INFO                        110
#define IDD_NUMFILES                    200
#define MAIN_HEIGHT                     200
#define IDD_XCORD                       210
#define IDD_YCORD                       220
#define MAIN_WIDTH                      400
#define _APS_NEXT_CONTROL_VALUE         1000
