//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by SHOWDIB.RC
//
#define IDM_ANIMATE5                    5
#define IDM_ANIMATE20                   20
#define IDM_ANIMATE50                   50
#define IDM_ANIMATE100                  100
#define ABOUTBOX                        100
#define DLGOPEN_EDIT                    101
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define DLGOPEN_FILE_LISTBOX            102
#define _APS_NEXT_RESOURCE_VALUE        102
#define DLGOPEN_DIR_LISTBOX             103
#define DLGOPEN_PATH                    104
#define DLGOPEN_TEXT                    105
#define DLGOPEN_FOLDOUT                 106
#define DLGOPEN_BIG                     107
#define DLGOPEN_SMALL                   108
#define IDM_ANIMATE200                  200
#define IDM_UPDATECOL                   1000
#define _APS_NEXT_CONTROL_VALUE         1000
#define IDM_ANIMATE0                    1001
#define IDM_OPEN                        1002
#define IDM_EXIT                        1003
#define IDM_ABOUT                       1004
#define IDM_DIBSCREEN                   1005
#define IDM_NOUGLY                      1006
#define IDM_STEALCOL                    1009
#define IDM_PRINT                       1010
#define IDM_COPY                        1012
#define IDM_MEMORYDIB                   1014
#define IDM_SAVE                        1015
#define IDM_TRANSPARENT                 1016
#define IDM_PASTEDIB                    1020
#define IDM_PASTEDDB                    1021
#define IDM_PASTEPAL                    1022
#define IDI_APP                         2000
#define IDM_ANIMATE201                  32000
