//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by EXPENSE.RC
//
#define menuMain                        1
#define miFile                          100
#define miExit                          101
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define miClearAll                      102
#define _APS_NEXT_RESOURCE_VALUE        102
#define miClearSig                      103
#define miAbout                         104
#define miNextField                     105
#define miPrecField                     106
#define _APS_NEXT_CONTROL_VALUE         1000
