//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by BLANDMDI.RC
//
#define IDS_CLIENTTITLE                 16
#define IDS_UNTITLED                    17
#define IDS_APPNAME                     18
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_CONTROL_VALUE         1000
#define IDM_FILENEW                     1001
#define IDM_FILEEXIT                    1006
#define IDM_WINDOWTILE                  4001
#define IDM_WINDOWCASCADE               4002
#define IDM_WINDOWCLOSEALL              4003
#define IDM_WINDOWICONS                 4004
#define IDM_WINDOWCHILD                 4100
