//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by DDEMLCLK.RC
//
#define IDS_ABOUTMENU                   1
#define IDS_APPNAME                     2
#define IDS_DATA                        3
#define IDS_TOOMANY                     4
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_CONTROL_VALUE         1000
#define IDM_ABOUT                       1001
