//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by LOWPASS.RC
//
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define _APS_NEXT_CONTROL_VALUE         1000

// /* Constants for dialogs.
// */
#define IDM_ABOUT       11          // menu items

#define ID_INPUTFILEEDIT    101     // input file name edit box
#define ID_OUTPUTFILEEDIT   102     // output file name edit box
