//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by GDOSMEM.RC
//
#define IDM_ABOUT                       100
#define IDM_ALLOC                       101
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define IDM_INT                         102
#define _APS_NEXT_RESOURCE_VALUE        102
#define IDM_FREE                        103
#define _APS_NEXT_CONTROL_VALUE         1000
