//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by CLIENT.RC
//
#define IDC_CANCEL                      0
#define IDC_OK                          1
#define IDM_INITIATE                    100
#define IDM_TERMINATE                   101
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define IDM_ADVISE                      102
#define IDM_UNADVISE                    103
#define IDM_REQUEST                     104
#define IDM_POKE                        105
#define IDM_PASTELINK                   106
#define IDM_CLEAR                       107
#define IDM_EXECUTE                     108
#define IDM_ABOUT                       109
#define IDC_APPLICATION                 200
#define IDC_TOPIC                       201
#define IDC_CONVBOX                     202
#define IDC_ITEM                        203
#define IDC_ITEMBOX                     204
#define IDC_VALUE                       205
#define IDC_EXECUTE_STRING              206
#define _APS_NEXT_CONTROL_VALUE         1000
