//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by SERVER.RC
//
#define IDM_COPY                        100
#define IDM_ABOUT                       101
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define ID_TAB                          200
#define ID_SHIFT_TAB                    201
#define _APS_NEXT_CONTROL_VALUE         1000
