//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by MAKEAPP.RC
//
#define IDR_MAINMENU                    1
#define IDR_MAINACCEL                   1
#define CMD_FILENEW                     100
#define IDR_MAINICON                    100
#define CMD_FILEOPEN                    101
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define CMD_FILESAVE                    102
#define _APS_NEXT_RESOURCE_VALUE        102
#define CMD_FILESAVEAS                  103
#define CMD_FILEPRINT                   120
#define CMD_FILEPRINTPREVIEW            121
#define CMD_FILEPRINTERSETUP            122
#define CMD_FILEEXIT                    130
#define CMD_EDITUNDO                    200
#define IDR_ABOUTDLG                    200
#define CMD_EDITREPEAT                  201
#define CMD_EDITCUT                     202
#define CMD_EDITCOPY                    203
#define CMD_EDITPASTE                   204
#define CMD_EDITCLEAR                   205
#define CMD_EDITPASTELINK               206
#define CMD_SAMPLEDLG                   300
#define IDR_SAMPLEDLG                   300
#define CTL_EDIT1                       301
#define CTL_EDIT2                       302
#define CTL_RED                         303
#define CTL_BLUE                        304
#define CTL_GREEN                       305
#define CTL_PURPLE                      306
#define CTL_MAUVE                       307
#define CTL_ECRU                        308
#define CTL_SIENNA                      309
#define CMD_HELPINDEX                   900
#define CMD_HELPKEYBOARD                901
#define CMD_HELPCOMMANDS                902
#define CMD_HELPPROCEDURES              903
#define CMD_HELPUSINGHELP               904
#define CMD_HELPABOUT                   905
#define _APS_NEXT_CONTROL_VALUE         1000
