//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by TIMERS.RC
//
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define _APS_NEXT_RESOURCE_VALUE        102
#define cmdStop                         0x200
#define cmdToHwnd                       0x201
#define cmdCallProc                     0x202
#define cmdSlow                         0x203
#define cmdMedium                       0x204
#define cmdFast                         0x205
#define _APS_NEXT_CONTROL_VALUE         1000
