//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by BITMAP.RC
//
#define IDM_ABOUT                       100
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define _APS_NEXT_RESOURCE_VALUE        102
#define IDM_BITMAP1                     200
#define IDM_BITMAP2                     201
#define IDM_BITMAP3                     202
#define IDM_PATTERN1                    300
#define IDM_PATTERN2                    301
#define IDM_PATTERN3                    302
#define IDM_PATTERN4                    303
#define IDM_BLACKONWHITE                400
#define IDM_WHITEONBLACK                401
#define IDM_COLORONCOLOR                402
#define _APS_NEXT_CONTROL_VALUE         1000
