//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by VERSTAMP.RC
//
#define IDM_ABOUT                       100
#define DLG_WINDIR                      100
#define IDM_FILEOPEN                    101
#define DLG_SYSDIR                      101
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define IDM_EXIT                        102
#define DLG_SRCFILENAME                 102
#define _APS_NEXT_RESOURCE_VALUE        102
#define DLG_SRCDIRNAME                  103
#define DLG_SRCFILEVER                  104
#define DLG_SRCPRODVER                  105
#define DLG_SRCFILEFLAG                 106
#define DLG_SRCOS                       107
#define DLG_SRCFILETYPE                 108
#define DLG_SRCSUB                      109
#define DLG_SRCLANGUAGE                 110
#define DLG_DSTFILENAME                 111
#define DLG_DSTDIRNAME                  112
#define DLG_DSTFILEVER                  113
#define DLG_DSTPRODVER                  114
#define DLG_DSTFILEFLAG                 115
#define DLG_DSTFILEOS                   116
#define DLG_DSTFILETYPE                 117
#define DLG_DSTSUB                      118
#define DLG_DSTLANGUAGE                 119
#define DLG_COMPANYNAME                 120
#define DLG_FILEDESCRIPTION             121
#define DLG_FILEVERSION                 122
#define DLG_INTERNALNAME                123
#define DLG_COPYRIGHT                   124
#define DLG_TRADEMARKS                  125
#define DLG_PRODUCTNAME                 126
#define DLG_PRODUCTVERSION              127
#define IDD_MOREINFO                    202
#define IDD_VERINSTALL                  203
#define IDD_ICON                        205
#define _APS_NEXT_CONTROL_VALUE         1000
