//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by EDITFILE.RC
//
#define IDM_NEW                         100
#define IDM_OPEN                        101
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define IDM_SAVE                        102
#define _APS_NEXT_RESOURCE_VALUE        102
#define IDM_SAVEAS                      103
#define IDM_PRINT                       104
#define IDM_EXIT                        105
#define IDM_ABOUT                       106
#define IDM_UNDO                        200
#define IDM_CUT                         201
#define IDM_COPY                        202
#define IDM_PASTE                       203
#define IDM_CLEAR                       204
#define IDC_EDIT                        401
#define _APS_NEXT_CONTROL_VALUE         1000
