//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by SCRIBBLE.RC
//
#define IDR_MAINFRAME                   2
#define IDR_SCRIBTYPE                 3
#define IDD_ABOUTBOX                    100
#define ID_PEN_THICK_OR_THIN            32768
#define ID_PEN_WIDTHS                   32769
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         32770
#define _APS_NEXT_CONTROL_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
