//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by SORTDEMO.RC
//
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define _APS_NEXT_CONTROL_VALUE         1000


////////////////////////////////////////////////////////////////////////////
//  MENU CONTROL VALUES

#define IDM_EXIT        10

#define IDM_RAND		20
#define IDM_SOUND		21
#define IDM_PAUSE		22
#define IDM_STATS	    23

#define IDM_INSERT		31
#define IDM_BUBBLE		32
#define IDM_HEAP		33
#define IDM_EXCHANGE	34
#define IDM_SHELL		35
#define IDM_QUICK		36


#define IDM_ABOUT       40

////////////////////////////////////////////////////////////////////////////
//  STATS AND PAUSE DIALOG BOX VALUES

#define ID_I_TIME                   111
#define ID_I_SWAP                   112
#define ID_I_COMPARE                113
#define ID_B_TIME                   114
#define ID_B_SWAP                   115
#define ID_B_COMPARE                116
#define ID_H_TIME                   117
#define ID_H_SWAP                   118
#define ID_H_COMPARE                119
#define ID_E_TIME                   120
#define ID_E_SWAP                   121
#define ID_E_COMPARE                122
#define ID_S_TIME                   123
#define ID_S_SWAP                   124
#define ID_S_COMPARE                125
#define ID_Q_TIME                   126
#define ID_Q_SWAP                   127
#define ID_Q_COMPARE                128
#define ID_PAUSE                    200
#define ID_SLOWER                   201
#define ID_FASTER                   202

