//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by SRVRDEMO.RC
//
#define IDM_NEW                         100
#define IDM_OPEN                        101
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define IDM_SAVE                        102
#define _APS_NEXT_RESOURCE_VALUE        102
#define IDM_SAVEAS                      103
#define IDM_EXIT                        104
#define IDM_ABOUT                       105
#define IDM_UPDATE                      106
#define IDM_CUT                         107
#define IDM_COPY                        108
#define IDM_DELETE                      109
#define IDM_RED                         110
#define IDM_GREEN                       111
#define IDM_BLUE                        112
#define IDM_WHITE                       113
#define IDM_GRAY                        114
#define IDM_CYAN                        115
#define IDM_MAGENTA                     116
#define IDM_YELLOW                      117
#define IDM_NEWOBJ                      118
#define IDM_NEXTOBJ                     119
#define IDD_CONTINUEEDIT                120
#define IDD_UPDATEEXIT                  121
#define IDD_TEXT                        122
#define _APS_NEXT_CONTROL_VALUE         1000
