//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by MULTIPAD.RC
//
#define IDR_MAINFRAME                   1
#define IDR_TEXTTYPE                    2
#define IDD_ABOUTBOX                    512

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         32769
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
