//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by CROPDIB.RC
//
#define ABOUTBOX                        1
#define CROPDIBBOX                      2
#define IDM_ABOUT                       11
#define ID_INPUTFILEEDIT                101
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define ID_OUTPUTFILEEDIT               102
#define _APS_NEXT_RESOURCE_VALUE        102
#define ID_XEDIT                        103
#define ID_YEDIT                        104
#define ID_WEDIT                        105
#define ID_HEDIT                        106
#define ID_BRIGHTEDIT                   107
#define ID_STATUSTEXT                   108
#define IDS_APPNAME                     300
#define IDS_CANTOPENFILE                301
#define IDS_ERRORWRITING                302
#define IDS_ERRORREADING                303
#define IDS_OUTOFMEMORY                 304
#define IDS_INTERNALERROR               305
#define IDS_CANTLOADDIBDRV              306
#define IDS_FORMATNOTSUPPORTED          307
#define _APS_NEXT_CONTROL_VALUE         1000
