//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by HOOKS.RC
//
#define IDM_ABOUT                       100
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define _APS_NEXT_RESOURCE_VALUE        102
#define IDM_CALLWNDPROC                 200
#define IDM_CBT                         201
#define IDM_GETMESSAGE                  202
#define IDM_JOURNALPLAYBACK             203
#define IDM_JOURNALRECORD               204
#define IDM_KEYBOARD                    205
#define IDM_MOUSE                       206
#define IDM_MSGFILTER                   207
#define IDM_SYSMSGFILTER                208
#define _APS_NEXT_CONTROL_VALUE         1000
