//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by HELPHOOK.RC
//
#define helphook                        33
#define IDM_ABOUT                       100
#define IDM_DLG1                        101
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define IDM_DLG2                        102
#define _APS_NEXT_RESOURCE_VALUE        102
#define IDM_DLG3                        103
#define IDM_DLG4                        104
#define IDM_DLG5                        105
#define IDM_DLG6                        106
#define IDM_DLG7                        107
#define IDM_DLG8                        108
#define IDM_DLG9                        109
#define ID_HELP                         201
#define ID_HELPCONTEXT                  1000
#define _APS_NEXT_CONTROL_VALUE         1000
