//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by SCRIBBLE.RC
//
#define IDR_MAINFRAME                   2
#define IDR_SCRIBTYPE                 3
#define IDD_ABOUTBOX                    100
#define ID_PEN_THICK_OR_THIN            32768
#define ID_PEN_WIDTHS                   32769
#define IDD_PEN_WIDTHS                  101
#define IDC_THIN_PEN_WIDTH              104
#define IDC_THICK_PEN_WIDTH             105
#define IDC_DEFAULT_PEN_WIDTHS          106
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         32770
#define _APS_NEXT_CONTROL_VALUE         107
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
