//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by SNOOP.RC
//
#define menuSnoop                       1
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define _APS_NEXT_RESOURCE_VALUE        102
#define miHold                          1000
#define _APS_NEXT_CONTROL_VALUE         1000
#define miRelease                       1001
