//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by C:\SAMPLES\SAMPLES\MENU\MENU.RC
//
#define IDFILE_POS                      0
#define IDCOLORS_POS                    1
#define IDSTATES_POS                    2
#define IDHELP_POS                      3
#define MEASUREITEMWIDTH                40
#define MEASUREITEMHEIGHT               40
#define ID_ABOUT                        100
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define _APS_NEXT_RESOURCE_VALUE        103
#define IDM_EXIT                        202
#define IDM_ABOUT                       203
#define IDM_COLOROWNERDR                500
#define IDM_BLACK                       501
#define IDM_BLUE                        502
#define IDM_RED                         503
#define IDM_GREEN                       504
#define IDM_FONT                        600
#define IDM_SIZE                        601
#define IDM_STYLE                       602
#define IDM_STATE1                      610
#define IDM_STATE2                      611
#define IDM_STATE3                      612
#define IDM_STATE4                      613
#define _APS_NEXT_CONTROL_VALUE         1000
