# Makefile : Builds the helloapp application
#
# Usage:     NMAKE helloapp

# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (C) 1992 Microsoft Corporation
# All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and Microsoft
# WinHelp documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.
#

# Only retail build
helloapp.exe: helloapp.cpp helloapp.def
	cl /AM /O1 /F 1000 helloapp.def helloapp.cpp /link /ALIGN:4 /NOD /ONERROR:NOEXE mafxcw mlibcew libw shell commdlg

clean:
	-del helloapp.exe
	-del helloapp.map
	-del helloapp.obj
