//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by HANDTEST.RC
//
#define IDM_GET                         101
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define IDM_SET                         102
#define _APS_NEXT_RESOURCE_VALUE        102
#define IDM_RESTORE                     103
#define IDM_ABOUT                       104
#define _APS_NEXT_CONTROL_VALUE         1000
