[dosbox]
memsize=4
[cpu]
core=normal
cputype=pentium
cycles=max
[autoexec]
mount c work/release-test/ADINITST
c:
addini C:\ADINITST\WIN\SYSTEM.INI 386Enh device=ABIOSDSK.386
if errorlevel 7 echo 7>result.txt
if errorlevel 6 echo 6>result.txt
if errorlevel 5 echo 5>result.txt
if errorlevel 4 echo 4>result.txt
if errorlevel 3 echo 3>result.txt
if errorlevel 2 echo 2>result.txt
if not errorlevel 1 echo 0>result.txt
exit
