[dosbox]
memsize=4
[cpu]
core=normal
cputype=pentium
cycles=max
[autoexec]
mount c work/release-test
c:
cd \ADINITST
addini C:\ADINITST\WIN\SYSTEM.INI 386Enh device=ABIOSDSK.386
if errorlevel 7 echo ERROR7 > status.txt
if errorlevel 6 echo ERROR6 > status.txt
if errorlevel 5 echo ERROR5 > status.txt
if errorlevel 4 echo ERROR4 > status.txt
if errorlevel 3 echo ERROR3 > status.txt
if errorlevel 2 echo ERROR2 > status.txt
if not errorlevel 1 echo SUCCESS > status.txt
exit
