//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by PENAPP.RC
//
#define menuPenApp                      1
#define iconPenApp                      1
#define miExit                          100
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define _APS_NEXT_RESOURCE_VALUE        102
#define miSample                        200
#define miShape                         201
#define miSystem                        202
#define miSaveData                      203
#define _APS_NEXT_CONTROL_VALUE         1000
