//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by MCITEST.RC
//
#define IDD_ABOUTBOX                    1
#define IDD_MCITEST                     2
#define IDD_ERRORDLG                    3
#define IDD_DEVICES                     4
#define IDI_MCITEST                     5
#define IDM_MCITEST                     6
#define IDA_MCITEST                     7
#define MENU_OPEN                       10
#define MENU_SAVE                       11
#define MENU_SAVEAS                     12
#define MENU_ABOUT                      20
#define MENU_EXIT                       21
#define MENU_START_TEST                 22
#define MENU_DEVICES                    30
#define ID_INPUT                        101
#define DLGOPEN_STATIC                  101
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define ID_OUTPUT                       102
#define DLGOPEN_EDIT                    102
#define ID_ERRORCODE                    103
#define DLGOPEN_FILE_LISTBOX            103
#define ID_NOT_SUCCESS                  104
#define DLGOPEN_DIR_LISTBOX             104
#define _APS_NEXT_RESOURCE_VALUE        104
#define ID_NOT_SUPER                    105
#define DLGOPEN_PATH                    105
#define ID_NOT_ABORT                    106
#define ID_NOT_FAIL                     107
#define ID_DEVICE_LIST                  108
#define ID_END_DEVICE_LIST              109
#define ID_GO                           200
#define ID_STEP                         201
#define ID_EXIT                         202
#define ID_MCISENDSTR                   203
#define ID_MCIEXEC                      204
#define ID_RUNCOUNT                     205
#define _APS_NEXT_CONTROL_VALUE         1000
