// MASTER.H  - master list of includes shared by all projects.
//	this facilitates using pre-compiled headers by ensuring
//	that headers always appear in the same order in every file.

#include <windows.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <io.h>
#include <direct.h>
#include <memory.h>
#include <assert.h>
#include <stdlib.h>
#include "commdlg.h"
#include "about.h"
#include "capture.h"
#include "child.h"
#include "clipbrd.h"
#include "dib.h"
#include "dibview.h"
#include "dlgs.h"
#include "errors.h"
#include "file.h"
#include "frame.h"
#include "init.h"
#include "options.h"
#include "paint.h"
#include "palette.h"
#include "print.h"
